version: '3.7'

services:
  reverse-proxy:
    image: traefik:v2.0
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reverse-proxy
  nextjs:
    container_name: nextjs
    build: .
    expose:
      - '3000'
    environment:
      - NODE_ENV=deployment
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`arnoldjoslive.com`, `www.arnoldjoslive.com`)"
      - "traefik.http.routers.nextjs.entrypoints=web"
    networks:
      - reverse-proxy

networks:
  reverse-proxy: